import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink, GitMerge, History, Instagram, MapPin, Network, NotebookPen, ShieldCheck } from "lucide-react";
import AppShell from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getRadarEntityDetail } from "@/lib/radar-hub/data";
import { ENTITY_TYPE_LABELS, RADAR_CATEGORY_LABELS, type TerritorialInfluenceBreakdown } from "@/lib/radar-hub/types";
import { requireInternalPageSession } from "@/lib/supabase/auth";
import { EntityActions, MergeActions } from "./entity-actions";

export const dynamic = "force-dynamic";
function percent(value: number) { return `${Math.round(value * 100)}%`; }
function scoreBreakdown(value: unknown): TerritorialInfluenceBreakdown | null { return value && typeof value === "object" && "total" in value ? value as TerritorialInfluenceBreakdown : null; }
export default async function EntityPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; await requireInternalPageSession(`/dashboard/inteligencia/entidades/${id}`);
  const detail = await getRadarEntityDetail(id); if (!detail) notFound();
  const { entity } = detail; const breakdown = scoreBreakdown(entity.influence_score_breakdown);
  return <AppShell><PageHeader eyebrow="Entidade unificada" title={entity.display_name} description={`${ENTITY_TYPE_LABELS[entity.entity_type]} · ${RADAR_CATEGORY_LABELS[entity.main_category]}`} action={<Button variant="outline" nativeButton={false} render={<Link href="/dashboard/inteligencia" />}><ArrowLeft data-icon="inline-start" />Voltar</Button>} />
    <div className="grid gap-6 pb-12 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2">
      <Card><CardHeader><CardTitle>Visão consolidada</CardTitle><CardDescription>{entity.description ?? "Sem descrição comprovada."}</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><p><span className="block text-xs uppercase text-muted-foreground">Localização</span><span className="flex items-center gap-2 font-bold"><MapPin className="size-4" />{entity.primary_city ?? "Não inferida"}{entity.primary_state ? `/${entity.primary_state}` : ""}</span></p><p><span className="block text-xs uppercase text-muted-foreground">Confiança da localização</span><span className="font-mono font-bold">{percent(entity.location_confidence)}</span></p><p><span className="block text-xs uppercase text-muted-foreground">Confiança geral</span><span className="font-mono font-bold">{percent(entity.confidence_score)}</span></p><p><span className="block text-xs uppercase text-muted-foreground">Status</span><Badge variant="secondary">{entity.status}</Badge></p></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck />Score territorial: {entity.influence_score.toFixed(1)}</CardTitle><CardDescription>Composição explicável; ausência de dados reduz o score e nunca é preenchida por invenção.</CardDescription></CardHeader><CardContent>{breakdown ? <div className="grid gap-3 sm:grid-cols-2">{Object.entries({ "Alcance digital": breakdown.digital_reach, "Relevância regional": breakdown.regional_relevance, "Relevância institucional": breakdown.institutional_relevance, Rede: breakdown.network, Engajamento: breakdown.engagement, "Qualidade dos dados": breakdown.data_quality }).map(([label, value]) => <div key={label} className="flex justify-between border-b border-cement pb-2"><span>{label}</span><strong className="font-mono">{value.toFixed(1)}</strong></div>)}<ul className="sm:col-span-2 list-disc pl-5 text-sm text-muted-foreground">{breakdown.explanation.map((item) => <li key={item}>{item}</li>)}</ul></div> : <p className="text-muted-foreground">Detalhamento ainda não calculado.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Evidências e identificadores</CardTitle><CardDescription>{detail.evidence.length} evidências com origem e confiança.</CardDescription></CardHeader><CardContent className="space-y-4">{detail.identifiers.map((item) => <div className="flex flex-wrap items-center justify-between gap-2 border-b border-cement pb-3" key={item.id}><span><Badge variant="outline">{item.source_type}</Badge> {item.identifier_value}</span>{item.url ? <a className="inline-flex items-center gap-1 text-sm text-burnt-yellow" href={item.url} rel="noreferrer" target="_blank">Abrir <ExternalLink className="size-3" /></a> : null}</div>)}{detail.evidence.map((item) => <div className="rounded-[4px] border-2 border-cement p-3" key={item.id}><div className="flex justify-between gap-2"><strong>{item.field_name}</strong><Badge variant="secondary">{percent(item.confidence)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.source_name} · {new Date(item.captured_at).toLocaleString("pt-BR")}</p><p className="mt-2 break-words text-sm">{item.raw_excerpt ?? JSON.stringify(item.field_value)}</p></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Network />Relações</CardTitle></CardHeader><CardContent className="space-y-3">{detail.relationships.length ? detail.relationships.map((relation) => { const otherId = relation.subject_entity_id === id ? relation.object_entity_id : relation.subject_entity_id; const other = detail.relatedEntities[otherId]; return <div key={relation.id} className="flex flex-wrap justify-between gap-2 border-b border-cement pb-3"><span><strong>{relation.predicate}</strong> · {other?.display_name ?? otherId}</span><Badge variant="outline">{percent(relation.confidence)}</Badge></div>; }) : <p className="text-muted-foreground">Nenhuma relação comprovada.</p>}</CardContent></Card>
    </div><aside className="space-y-6">
      <Card><CardHeader><CardTitle>Ações</CardTitle></CardHeader><CardContent><EntityActions entityId={id} /></CardContent></Card>
      {detail.instagramProfile ? <Card><CardHeader><CardTitle className="flex items-center gap-2"><Instagram />Radar de Influência</CardTitle></CardHeader><CardContent><Button nativeButton={false} render={<Link href={`/dashboard/influencia/${detail.instagramProfile.id}`} />}>@{detail.instagramProfile.username}</Button></CardContent></Card> : null}
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><GitMerge />Possíveis duplicidades</CardTitle></CardHeader><CardContent className="space-y-4">{detail.mergeSuggestions.length ? detail.mergeSuggestions.map((suggestion) => <div key={suggestion.id} className="space-y-2 border-b border-cement pb-4"><p className="text-sm">{suggestion.suggested_reason}</p><Badge variant="outline">{percent(suggestion.confidence)} · {suggestion.status}</Badge>{suggestion.status === "pending" ? <MergeActions suggestionId={suggestion.id} /> : null}</div>) : <p className="text-sm text-muted-foreground">Sem sugestões pendentes.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><NotebookPen />Observações</CardTitle></CardHeader><CardContent className="space-y-3">{detail.notes.length ? detail.notes.map((note) => <div key={note.id} className="border-b border-cement pb-3"><p className="text-sm">{note.body}</p><span className="text-xs text-muted-foreground">{note.created_by_email ?? "Usuário interno"} · {new Date(note.created_at).toLocaleString("pt-BR")}</span></div>) : <p className="text-sm text-muted-foreground">Nenhuma observação.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><History />Histórico</CardTitle></CardHeader><CardContent className="space-y-3">{detail.history.length ? detail.history.map((item) => <div key={item.id} className="border-b border-cement pb-3"><p className="text-sm font-bold">{item.reason}</p><span className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString("pt-BR")}</span></div>) : <p className="text-sm text-muted-foreground">Sem alterações anteriores.</p>}</CardContent></Card>
    </aside></div>
  </AppShell>;
}
